format_version: v1.0
type: UniqueComponent
attributes: {id: drvExtPhyLan867x}
children:
- type: Symbols
  children:
  - type: Combo
    attributes: {id: DRV_ETHPHY_10BASE_T1S_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: PLCA}
  - type: Integer
    attributes: {id: PLCA_NODE_ID}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: libdrvExtPhyLan867x}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: drvGmac}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: GMAC_PHY_Dependency}
- type: ElementPosition
  attributes: {x: '400', y: '20', id: drvExtPhyLan867x}
