format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipDhcps}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: TCPIP_DHCPS_DEFAULT_IP_ADDRESS_RANGE_START_IDX0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 192.168.1.100}
  - type: Integer
    attributes: {id: TCPIP_DHCP_SERVER_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipDhcps, value: '492'}
- type: ElementPosition
  attributes: {x: '581', y: '20', id: tcpipDhcps}
